server.port: 8888

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: config-server 
    password: password

  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/config-server-files

management:
  security:
    enabled: false